# Generated by Django 2.1.7 on 2019-03-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo_proprietario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='nome',
            new_name='marca',
        ),
    ]
