# Generated by Django 2.1.7 on 2019-04-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto1', models.TextField(max_length=1000)),
                ('texto2', models.TextField(max_length=1000)),
                ('texto3', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PlanosPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto1', models.TextField(max_length=1000)),
                ('texto2', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto1', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='SobrePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto1', models.TextField(max_length=1000)),
                ('texto2', models.TextField(max_length=1000)),
            ],
        ),
    ]
