# Generated by Django 2.1.7 on 2019-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_homepage_planospage_servicopage_sobrepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='texto1',
            new_name='linha1coluna1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='texto2',
            new_name='linha1coluna2',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='texto3',
            new_name='linha2coluna1',
        ),
        migrations.RenameField(
            model_name='planospage',
            old_name='texto1',
            new_name='linha1',
        ),
        migrations.RenameField(
            model_name='planospage',
            old_name='texto2',
            new_name='linha2',
        ),
        migrations.RenameField(
            model_name='servicopage',
            old_name='texto1',
            new_name='textounico',
        ),
        migrations.RenameField(
            model_name='sobrepage',
            old_name='texto1',
            new_name='linha1',
        ),
        migrations.RenameField(
            model_name='sobrepage',
            old_name='texto2',
            new_name='linha2',
        ),
        migrations.AddField(
            model_name='homepage',
            name='linha2coluna2',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='linha3coluna1',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='linha3coluna2',
            field=models.TextField(default='asdasd', max_length=1000),
            preserve_default=False,
        ),
    ]
